Controllers films users
MikhailKuznets/java-filmorate pull request #1
Opened 2022-09-09 15:39 UTC by MikhailKuznets

2022-09-10 17:36 UTC, andrew-larkin requested changes
Привет! Отличная реализация функционала + качественно написанные тесты. Используются аннотации свои собственные, а также ломбоковские - это большой плюс. Всего пару моментов доработать и работа будет принята.

2022-09-10 17:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильм с id = {} отсутствует в базе", film.getId());
здесь можно оставить что-нибудь одно, т.к. при ошибке обе записи попадут в консоль, а достаточно одной

2022-09-10 17:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            log.warn("Пользователь с id = {} отсутствует в базе", user.getId());
здесь тоже стоит оставить что-то одно. это должно быть исключение, само собой

2022-09-10 17:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String name;
может, сюда тоже какую-нибудь валидацию придумать, по типу CorrectLogin, чтобы не оставлять лишние проверки в контроллере?

2022-09-10 17:36 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private MockMvc mockMvc;
за mockMvc отдельный плюс!

2022-09-10 17:36 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        User user = User.builder()
из раза в раз повторяется создание одних и тех же юзеров - попробуй вынести этот функционал в отдельный метод, чтобы не дублировать код

2022-09-10 17:36 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Film updatedFilm = new Film("Updated Film Name",
объект встречается  в нескольких тестах, предлагаю вынести создание объекта в отдельный метод

2022-09-12 13:34 UTC, MikhailKuznets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильм с id = {} отсутствует в базе", film.getId());
Исправил двойной логирование при неверном id

2022-09-12 13:35 UTC, MikhailKuznets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            log.warn("Пользователь с id = {} отсутствует в базе", user.getId());
и тут также подправил

2022-09-12 13:36 UTC, MikhailKuznets commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private MockMvc mockMvc;
Хорошие люди подсказали что с ним удобнее

2022-09-12 13:37 UTC, MikhailKuznets commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        User user = User.builder()
Согласен, так будет логичнее

2022-09-12 13:38 UTC, MikhailKuznets commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Film updatedFilm = new Film("Updated Film Name",
И тут аналогично поправлю

2022-09-20 13:37 UTC, merged